language: rust
cache:
  directories:
    - $HOME/.cargo
    - $HOME/libsodium

branches:
  only:
    - master
    - travis-ci

rust:
  - 1.34.1
  - stable

os:
  - linux
  - osx

matrix:
  include:
    - os: linux
      dist: xenial

addons:
  apt:
    packages:
      - libssl1.0.0
      - libssl-dev

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew link --force openssl  ; fi
  - if [ ! -d "$HOME/.libsodium/lib" ]; then curl -fsSL https://download.libsodium.org/libsodium/releases/libsodium-1.0.16.tar.gz | tar xz ; fi
  - if [ ! -d "$HOME/.libsodium/lib" ]; then cd libsodium-1.0.16 ; fi
  - if [ ! -d "$HOME/.libsodium/lib" ]; then ./autogen.sh fi
  - if [ ! -d "$HOME/.libsodium/lib" ]; then ./configure --prefix=$HOME/.libsodium fi
  - if [ ! -d "$HOME/.libsodium/lib" ]; then make && make install fi

env:
  - SODIUM_LIB_DIR=$HOME/.libsodium/lib LD_LIBRARY_PATH=$HOME/.libsodium/lib

install:
  - rustup component add rustfmt
  - rustup component add clippy
  - rustup target add wasm32-unknown-unknown
  - command -v cargo-audit >/dev/null 2>&1 || cargo install cargo-audit

script:
  - cargo fmt --all -- --check
  - cargo clippy --all
  - cargo check
  - cargo audit
  - cargo build
  - cargo build --manifest-path=libursa/Cargo.toml --no-default-features --features=portable
  - cargo test
  - cargo doc --no-deps
