language: rust
cache: cargo

branches:
  only:
    - master

rust:
  - stable

os:
  - linux

addons:
  apt:
    packages:
      - libssl1.0.0
      - libssl-dev

env:
  - SODIUM_BUILD_STATIC=1

script:
  - cargo build
  - cargo build --no-default-features --features=portable
  - cargo test --release
  - cargo run --manifest-path ./libursa/Cargo.toml --bin test_secp256k1 --features="benchmarksecp256k1"
  - cargo run --manifest-path ./libursa/Cargo.toml --bin test_ed25519 --features="benchmarked25519"
