[package]
authors = ["The Hyperledger Ursa Contributors"]
description = "Core functionality shared across all ursa components"
edition = "2018"
license = "Apache-2.0"
name = "ursa_core"
readme = "../README.md"
version = "0.5.0"

[dependencies]
