//! This crate contains shared components used among the
//! Ursa library

#![deny(
    unused_variables,
    unused_imports,
    unused_import_braces,
    unused_parens,
    unused_lifetimes,
    unconditional_recursion,
    unused_extern_crates,
    trivial_casts,
    trivial_numeric_casts
)]
#![cfg_attr(docsrs, feature(doc_cfg))]

mod error;

pub use serde;
pub use serde_bare;
pub use serde_cbor;
pub use serde_json;

/// The errors generated by ursa components
pub use error::*;
