[package]
authors = ["The Hyperledger Ursa Contributors"]
description = "Cryptography for encrypting data"
edition = "2018"
license = "Apache-2.0"
name = "ursa_encryption"
readme = "../README.md"
version = "0.5.0"

[dependencies]
